  GNU nano 8.4                                                                     mkdocs.yml *
site_name: Dylan's Docs

theme:
  name: material
  custom_dir: overrides
  font:
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# repo_url: https://github.com/dover20/mkdocs

markdown_extensions:
  # Tool tips
  - content.tooltips
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # tables
  - tables
  # Grids
  - attr_list
  - md_in_html
  - def_list
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # formatting / highlighting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Footnotes
  - footnotes
  # Mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - offline
  - search
